### ISSUE TITLE
[ArchLinux] Poor performance working with Samba

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/dde-file-manager#24]
I'm testing this feature because I need it in my job, but I find some bad issues:

Initially, it has a poor interface compared with `gnome` interface:
![invisible](https://user-images.githubusercontent.com/5034215/42278714-66e9fd3a-7fa4-11e8-9794-89d9f85fb45f.png)
![gnomesamba](https://user-images.githubusercontent.com/5034215/42278678-4a8c7262-7fa4-11e8-86b4-038c569b1136.png)
`gnome` hud is more suitable and beautiful, you cannot see password letters in `deepin` hud, and also it has a useful help modal:
![ayudagnomesamba](https://user-images.githubusercontent.com/5034215/42278677-4a6a7086-7fa4-11e8-8a09-5dc06673fe5b.png)

But the worst problem is the performance:
![deepin-screen-recorder_select area_20180704160451](https://user-images.githubusercontent.com/5034215/42278844-a9fdb710-7fa4-11e8-9e07-07fb8e61dffb.gif)
![deepin-screen-recorder_select area_20180704160222](https://user-images.githubusercontent.com/5034215/42278845-aa71722c-7fa4-11e8-8c2b-9698a228953c.gif)
You can compare `nautilus` with `file manager`: it's faster, it does not show the problem at opening the `excel` file, and you can find the last visited folder in the main page.

This is the `excels` bug: 
![deepinsambaerror](https://user-images.githubusercontent.com/5034215/42278812-96a0d5da-7fa4-11e8-9d40-9b532b153dcd.png)

The main problem with this is that to work correctly with the folders of the windows network it is necessary to use `nautilus`, but this has conflicts with `file-manager`, consisting of `nautilus` stealing "privileges" from `file-manager`, so to speak; for example, here `nautilus` uses the icons chosen for the `deepin-desktop` while `file-manager` uses the icons chosen for `gnome-desktop`, that's why it is not a good idea install both in a system.
![problemafinalnautilusfilemanager](https://user-images.githubusercontent.com/5034215/42279845-bb1d4544-7fa7-11e8-922d-059ae56b277b.png)

**UPDATE:**  
The problem that i commented above is not related to this project, it is related with `deepin-dektop`.

**Comment by BLumia** [comment]
Hi and infact we are already working on that, in the current development branch we already fixed some issue you've mentioned, like the password preview font size issue and that auth dialog (here is a recent screenshot: 

![dfmrudlg](https://user-images.githubusercontent.com/10095765/42252545-b7766cdc-7f6f-11e8-8804-4d7e7bd7350d.png)

Some bug caused by gvfs may be solved after we switching to udisks2, we are also already working on that, so please wait for future update :) 

btw, actually `dde-desktop` is a part of `dde-file-manager`.

----

About the icon theme issue, if you are using linux deepin and installing nautilus fron the package manager, it should works fine without problem about the icon theme. I'm not sure with Arch packaging and if it is a issue. Maybe you should try fix it by yourself or report it to the icon theme releated package's maintainer from Arch community.

**Comment by SalahAdDin** [comment]
@BLumia, icon's problem happens with all icon themes; i installed `Antergos` `gnome` before installing `deepin`. I think it mays a conflict issue.

**Comment by BLumia** [comment]
Hi and the issues you've mentioned like the password label, i18n text support, performance and system icon theme support have been solved / enhanced in the current newest release (v1.8). Please wait for upstream package manager release the update for your distro.

We also prefer smaller issue report with more detail over large, monolithic issue report. That will make issue tracking much more easy.

**Comment by SalahAdDin** [comment]
@BLumia I'm still having the same performance problem with _file-manager_, `nautilus` still has better performance.
