### ISSUE TITLE
Deepin File Manager does not work with sftp

### ISSUE THREAD

**Issue by igatjens** [linuxdeepin/dde-file-manager#313]
Deepin File Manager connects to the sftp server, but when I try to navigate the folders by opening them by double clicking, it shows a message that says: "Unable to access sftp: host = tardis.local".

![image](https://user-images.githubusercontent.com/66392244/101065955-68b63600-355b-11eb-8e06-09c6710a5bf3.png)

I used nautilus to check if nautilus also showed the same error, but with nautilus sftp access worked without problems. So I can say that the server is not the problem.

I attach a video in the following compressed file where I show the test and the behavior of the problem.

[Captura de pantalla_área-de-selección_20201203105542.zip](https://github.com/linuxdeepin/dde-file-manager/files/5637895/Captura.de.pantalla_area-de-seleccion_20201203105542.zip)

I am using Deepin 20 1003 build 11031.106 and dde-file-manager 5.2.0.82-1.

![image](https://user-images.githubusercontent.com/66392244/101067091-b8493180-355c-11eb-8c2f-429f49824ffd.png)

I also attach the file generated when executing deepin-feedback-cli

[deepin-feedback-cli-Deepin-20-all-20201203-105945.tar.gz](https://github.com/linuxdeepin/dde-file-manager/files/5637917/deepin-feedback-cli-Deepin-20-all-20201203-105945.tar.gz)

**Comment by deepin-CD** [comment]
This bug has been fixed in the latest version！

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.

**Comment by jcnmsg** [comment]
I'm still experiencing this on the latest version (5.2.0.87-1). It connects to the SFTP server and I can navigate fine but the dialog keeps popping up over and over again as I navigate.

**Comment by regololab** [comment]
Unfortunately I have the same problem with version:
deepin 20.1 build 11038.003

**Comment by deepin-CD** [comment]
@regololab What's  the version number of the dde-file-manager you are using?

**Comment by regololab** [comment]
dde-file-manager version 5.2.0.87

**Comment by deepin-CD** [comment]
@regololab We did not fix it on 5.2.0.87.
Please upgrade dde-file-manager.

**Comment by regololab** [comment]
@deepin-CD 
I did a general upgrade, but the distribution crashed (Kernel panic).
I try to download version 20.2. I hope to be luckier :-)

**Comment by regololab** [comment]
I installed the new version 20.2 and everything seems to be ok

**Comment by deepin-CD** [comment]
Glad to hear the good news, many thanks for your feedback. You can close this issue, and reopen it if there are any new updates.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
